-- Migration: 003_create_patients.up.sql
-- Core patient demographic records. Central table — almost every other table FKs into this.
-- Contains PII: SSN, name, address, LAT/LON. Flag appropriately in context.yaml.

CREATE TABLE IF NOT EXISTS patients (
    Id                   VARCHAR(36)     NOT NULL,
    BIRTHDATE            DATE            NOT NULL,
    DEATHDATE            DATE,
    SSN                  VARCHAR(20)     NOT NULL COMMENT 'PII: Social Security Number (synthetic)',
    DRIVERS              VARCHAR(50)     COMMENT 'PII: Drivers license number',
    PASSPORT             VARCHAR(50)     COMMENT 'PII: Passport number',
    PREFIX               VARCHAR(20),
    FIRST                VARCHAR(100)    NOT NULL COMMENT 'PII: Given name',
    LAST                 VARCHAR(100)    NOT NULL COMMENT 'PII: Family name',
    SUFFIX               VARCHAR(20),
    MAIDEN               VARCHAR(100)    COMMENT 'PII: Maiden name',
    MARITAL              VARCHAR(5)      COMMENT 'M = married, S = single',
    RACE                 VARCHAR(50),
    ETHNICITY            VARCHAR(50),
    GENDER               VARCHAR(1)      NOT NULL COMMENT 'M or F',
    BIRTHPLACE           VARCHAR(255)    COMMENT 'PII: City and country of birth',
    ADDRESS              VARCHAR(255)    COMMENT 'PII: Current street address',
    CITY                 VARCHAR(100),
    STATE                VARCHAR(100),
    COUNTY               VARCHAR(100),
    ZIP                  VARCHAR(20)     COMMENT 'PII: Postal ZIP code',
    LAT                  DECIMAL(18,15)  COMMENT 'PII: Geographic latitude — can re-identify when combined',
    LON                  DECIMAL(18,15)  COMMENT 'PII: Geographic longitude — can re-identify when combined',
    HEALTHCARE_EXPENSES  DECIMAL(12,4)   NOT NULL DEFAULT 0 COMMENT 'Sensitive: total lifetime out-of-pocket expenses in USD',
    HEALTHCARE_COVERAGE  DECIMAL(12,4)   NOT NULL DEFAULT 0 COMMENT 'Sensitive: total lifetime insurance-covered amount in USD',

    PRIMARY KEY (Id),
    INDEX idx_last_first       (LAST, FIRST),
    INDEX idx_ssn              (SSN),
    INDEX idx_state_city       (STATE, CITY),
    INDEX idx_zip              (ZIP),
    INDEX idx_birthdate        (BIRTHDATE),
    INDEX idx_gender           (GENDER),
    INDEX idx_race_ethnicity   (RACE, ETHNICITY),
    INDEX idx_alive            (DEATHDATE)   -- NULL = alive; useful for filtering living patients

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Synthetic patient demographics generated by Synthea. Central entity for all clinical data.';
